### ISSUE TITLE
Add try/except blocks for safety

### ISSUE THREAD

**Issue by klahnakoski** [klahnakoski/TestLog-ETL#12]
Add some try/except blocks, possibly around the method-level loop, to catch any number of logic and data errors.  The objective is to process as much of the data as possible, and raise `Log.warning()` when things do not go as expected.  

Due to the amount if indenting, you may consider putting the body of into a separate method

```
for method_name, method_lines in obj.methods.iteritems():
```

**Comment by chinhodado** [comment]
Should I try/except at the method level? If I do that, and if there's an exception while processing the method, then the orphaned lines calculation will/can be wrong. In fact I'm not sure how to handle the orphaned lines calculation in the event a method failed to be processed.

Also I'm using `etl_header_gen.next` to generate the `record_key`. If there's an exception, the record_key won't be used, which will make the validation failed because the keys won't be contiguous?

**Comment by klahnakoski** [comment]
Hmm, yes.   I would not worry too much about the orphaned lines being wrong; they will not be wrong by much and it will have no impact a the file-level.  It is the best we can do with bad data.

You can generate the `etl_header.next` as a near last step.

**Comment by chinhodado** [comment]
I added it: 4b6a5f07ddd0346ba51e7931362f074f2447cdec
Thank you for doing the method splitting.
