### ISSUE TITLE
Make `covered` an array of line numbers

### ISSUE THREAD

**Issue by marco-c** [klahnakoski/TestLog-ETL#16]
This way of storing the covered lines seems unefficient:
https://github.com/klahnakoski/ActiveData-ETL/blob/eb9be06de2a1accd8300fd06192404f614838178/activedata_etl/transforms/gcov_to_es.py#L234

Is it needed for some reason? @klahnakoski

**Comment by klahnakoski** [comment]
Unfortunately, it is needed because of query limitations in either ActiveData or Elasticsearch; we must have objects.  But, it is not inefficient: The file compression is good at removing this redundancy, and ES stores data in reverse-lookup tables; resulting in indexes nearly the same size.

I am sure we can find a solution to get rid of this ugliness, but it is a bit more involved.

**Comment by marco-c** [comment]
`uncovered` is currently an array of numbers, should we make it an array of `{'line': C}` like `covered`?

**Comment by klahnakoski** [comment]
No.  We would like the `covered` array to be simple values like `uncovered`; We are prevented from doing this because we run queries on the `covered` lines that are not done on the uncovered lines.

It is an unfortunate incongruity.

**Comment by klahnakoski** [comment]
I will keep this open.  It should be fixed, but is low priority.

**Comment by klahnakoski** [comment]
this has been fixed

**Comment by marco-c** [comment]
Great! So I'll have to update grcov too to remove the "line".
